### ISSUE TITLE
Simple request, ESC to dismiss or hide log view

### ISSUE THREAD

**Issue by latenitecali** [snowkit/atom-flow#12]
Or maybe a customizable keymap for this function. Thanks!

**Comment by jtruher** [comment]
In keymap.cson:
```
'atom-text-editor':
  'cmd-shift-y' : 'flow:toggle-log-view'
```

**Comment by latenitecali** [comment]
👍 thanks bud

**Comment by ruby0x1** [comment]
I somehow missed this, but I remember my thought at the time was that binding a very common key by default is a very bad idea, and I would instead opt to let the user add keys to their configuration as necessary for any above the required!
