### ISSUE TITLE
Path to haxelib should be configurable or use haxe plugin's value

### ISSUE THREAD

**Issue by jeremyfa** [snowkit/atom-flow#13]
`haxelib` is hardcoded in the atom flow plugin: https://github.com/snowkit/atom-flow/blob/65266746c6bf9a451f1079ebd87bb394b3c6ad9d/lib/flow-call.js#L17

Path to `haxelib` should either be configurable from flow plugin settings, or use the already available settings in haxe plugin.

This may be the cause of https://github.com/snowkit/atom-haxe/issues/47

**Comment by ruby0x1** [comment]
This should be fixed by https://github.com/snowkit/atom-flow/commit/bca05fcd33ada3d7613946c843ca246553222e25
