### ISSUE TITLE
configurable build_only flags

### ISSUE THREAD

**Issue by misterpah** [snowkit/atom-flow#19]
an external service is watching my build folder for auto refresh browser (web target)
would be happy if the plugin officially support configurable build_only flags in flow-state.js .

in the mean time, i'll hack it to make it work

**Comment by ruby0x1** [comment]
I'm not sure what you mean exactly just yet. There is a "build with files" options which is useful for that, and there's also a `--sync` flag (useful on cli) which has it's own filewatch and automatically syncs file nodes for you. There's [this example](http://snowkit.org/2015/01/26/web-livereload-example/) that covers what I usually do.

But I'm curious of an example of what you're looking for.

**Comment by misterpah** [comment]
awesome! this is exactly what i want to do.
I propose your example/guide should be the standard way we do things with
flow.

thanks!
