### ISSUE TITLE
Yarn run flow throws error

### ISSUE THREAD

**Issue by Aravindhan12** [snowkit/atom-flow#21]
.flowconfig:72 Unsupported option specified! (unsafe.enable_getters_and_setters)
error Command failed with exit code 8.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Flow bin version : 0.63.1

**Comment by ruby0x1** [comment]
flow is not typically run via npm or yarn, it is run via haxelib and makes some assumptions about that. Can you elaborate on what you're trying to do?

**Comment by ruby0x1** [comment]
Or is the error via atom itself?

**Comment by jeremyfa** [comment]
I think @Aravindhan12 expected _atom-flow_ to be related to Facebook's Flow (https://flow.org/en/), hence the _.flowconfig_ file etc...

**Comment by ruby0x1** [comment]
ahh, yes likely. They're unrelated, this is for https://github.com/snowkit/flow
