### ISSUE TITLE
When typing CTRL + B multiple times, multiple flow commands are running at the same time

### ISSUE THREAD

**Issue by jeremyfa** [snowkit/atom-flow#6]
Not sure if we want to fix that one, but it can be rather confusing when it happens as everything shows up on the same log console.

Maybe we should wait until the previous command is finished? Or explicitly stop the previous run if we launch a new one?

**Comment by ruby0x1** [comment]
It should behave the same was as sublime, running consecutive builds kills the first one.

It's in a todo here, so i'll close this one:
https://github.com/snowkit/atom-haxe/issues/12

**Comment by jeremyfa** [comment]
Allright, thanks!

**Comment by ruby0x1** [comment]
I updated it to mention this case a bit clearer too.
